
const StringConstants = {
  ADD_COMMENT:"Add Comment",
  MSG_DETAIL: "Message Details",
  INBOX: "Inbox",
  NOTIFICATIONS: "Notifications",
  ENTER_TEN_DIGIT: "Please enter 10 digit code",
  HOME: "Home",
  PLEASE_ADD_PAN: "Please add PAN and GST",
  SUCCESSFULLY: "Successfully",
  ADD_REP_SUCCESS: "Add Representative Successfully",
  ADD_COMP_SUCCESS: "Add Competitor Successfully",
  UPDATE_REP_SUCCESS: "Update Representative Successfully",
  UPDATE_COMP_SUCCESS: "Update Competitor Successfully",
  SOMETHING_WENT_WRONG: "Something went wrong",
  COMPETITOR: "Competitor",
  BCK_BTN: "Back",
  EDT: "EDIT",
  ADD_COMPETITOR_DETAIL: "Add Competitor Details",
  ADD_COMPETITOR: "Add Competitor",
  EDIT_CUSTOMER_REPRESENTATIVE: "Edit Customer Representative",
  ACTIVE: "Active",
  INACTIVE: "Inactive",
  DESIGNATION: "Designation",
  DEPARTMENT: "Department",
  ADDRESS: "Address",
  WHATSAPP_NUMBER: "Whatsapp Number",
  VISITING_CARD: "Visiting Card",
  ENTER_SAP_CODE: "Enter SAP Customer Code",
  PROJECT_DETAIL: "Project Details",
  PROCURED_PRODUCT: "Procured Products",
  PRICE_FEEDBACK: "Price Feedback of Competitor",
  TENTATIVE_PROCURED: "Tentative Quantity Procured",
  CUSTOMER_DETAIL: "Customer Details",
  REPRESENTATIVE_DETAILS: "Representative Details",
  COMPETITOR_DETAIL: "Competitor Details",
  CUSTOMER_PROFILE: "Customer Profiles",
  CUSTOMER_VIEW_PROFILE: "Customer View Profiles",
  ENTER_REASON: "Enter Reason*",
  INVALID_DETAIL: "Invalid detail *",
  REGION: "Region",
  NICK_NAME: "Nick Name",
  CUSTOMER_REGION: "Customer Region*",
  cancelled: "Cancelled",
  EDIT_VISIT: "Edit Visit",
  CANCEL_VISIT: "Cancel Visit",
  USER_ROLE: "Branch Manager",
  SEE_ALL: "See All",
  VIEW_ALL: "View All",
  CUSTOMER_INFORMATION: "Customer Information",
  CUSTOMER_TYPE: "Customer Type",
  CUSTOMER_STATUS: "Status of Customer",
  DISCUSSION_POINT: "Discussion Points",
  VISIT_TIME_DATE: "Visit Date and Time",
  ISSUE: "Issue",
  ESCALATION_DETAIL: "Escalation Details",
  ESCALATION_STATUS: "Escalation Status",
  MARKED_AS_RESOLVED: "Marked as resolved",
  COMMENT_BY_ESCALATED_MANAGER: "Comments by Escalated Manager",
  RESOLUTION_COMMMENTS: "Resolution Comments",
  CUSTOMER_MODE: "Customer Mode",
  CUSTOMER_CONTACT_DETAIL: "Customer Contact Detail",
  COMMENT_ON_SELECTED_ISSUE: "Comment on selected issue",
  ENQUIRY: "Enquiry",
  SETTINGS: "Setting",
  USER_NAME: "John Doe",
  WELCOME: "Welcome,\n",
  TRACK_SALES: "Track your sales meeting hassle free",
  EFFORTLESSLY_ORGANIZE: "Effortlessly organize and elevate your meetings",
  CREATE_ACCOUNT: "Create account",
  SIGN_IN: "Sign In",
  SIGN_UP: "Sign Up",
  ENTER_PERSONAL_INFO: "Enter your personal information",
  YOUR_UNIQUE: "Your Unique Personal No.",
  YOUR_NAME: "Your Name",
  CONTACT_NUMBER: "Your Contact Number",
  EMAIL_ID: "Your Email ID",
  ALREADY_ACCOUNT: "Already have an account? ",
  ENTER_BRANCH: "Enter you branch and role",
  LOCATION: "Location",
  YOUR_ROLE: "Your Role",
  CHOOSE_PASSWORD: "Choose a passowrd",
  CREATE_PASSWORD: "Create Your Password",
  YOUR_PASSWOD: "Your Password",
  CONFIRM_PASSWORD: "Confirm Your Password",
  PLEASE_ENTER_SIGNIN: "Please enter details to sign in",
  DONT_HAVE_ACCOUNT: "Don’t have an account? ",
  REMEMBER_ME: "Remember me",
  FORGOT_PASSWORD: "Forgot password?",
  OR: "Or",
  SIGNIN_FINGERPRINT: "Sign in with Fingerprint",
  SIGNIN_FACE_RECOGNITION: "Sign in with Face Recognition",
  RESET_PASSWORD: "Reset Password",
  PLEASE_ENTER_PERSONAL_INFO: "Please enter personal information",
  GET_OTP: "Get OTP",
  ENTER_OTP: "Enter OTP shared on your mobile number",
  CONTINUE: "Continue",
  ENTER_NEW_PASSWORD: "Enter Your New Password",
  RE_ENTER_NEW_PASSWORD: "Re-enter Your New Password",
  VISITS: "Visits",
  SEARCH: "Search",
  MORE_OPTION: "More Options",
  FROM: "From",
  TO: "To",
  PRODUCT_CATALOGUE: "Product Catalogue",
  DOWNLOAD_CATALOGUE: "Downlaod Catalogue",
  VISIT_PLAN_CREATED: "Visit plan created successfully.",
  CUSTOMER_CODE: "Customer Code ",
  ENTER_NAME: "Enter Name",
  ENTER_NICK_NAME: "Enter Nick Name*",
  SELECT_VISITING_EXECUTIVE: "Select Visiting Executive*",
  SELECT_REASON: "Select Reason*",
  SELECT_MODE_OF_CONTACT: "Select Mode of Contact*",
  MODE_OF_MEETING: "Mode of Meeting",
  VISIT_DATE: "Visit Date *",
  ENTER_REMARKS: "Enter Remarks *",
  REMARKS: "Remarks",
  SUBMIT: "Submit",
  CANCEL: "Cancel",
  BACK: "Back to home",
  LAST_VISIT: "Last Visit details of the customer",
  ENTER_CUSTOMER_CODE: "Enter 10 Digits Customer Code or Nickname",
  INVALID_UPN: "Invalid Unique Personal Number",
  INVALID_NAME: "Invalid Name",
  INVALID_CN: "Invalid Contact Number",
  INVALID_EMAIL: "Invalid Email Address",
  INVALID_CONFIRM_PASSWORD: "Invalid Confirm Password",
  PENDING_APPROVAL: "Pending Approval \n",
  ACCOUNT_PENDING: "Your account is pending for approval with admin.",
  PASSWORD_DIDNT_MATCH: "Password didn`t match!",
  _SETTINGS: "Settings",
  LOGOUT: "Logout",
  EDIT_PROFILE: "Edit Profile",
  UPN: "Unique Personal Number",
  NAME: "Name",
  CN: "Contact Number",
  EMAIL: "Email ID",
  ROLE: "Role",
  UPDATE_PROFILE: "Update Profile",
  UPDATE: "Update",
  CMS_PAGES: "CMS Pages",
  ABOUT_US: "About Us",
  CONTACT_US: "Contact Us",
  PRIVACY: "Privacy",
  FAQS:"FAQs",
  TERMS_AND_CONDITIONS: "Terms & Conditions",
  INVALID_CONTACT: "Invalid Contact Number",
  INVALID_PASSWORD: "Invalid Password!",
  INVALID_USER: "Invalid User",
  UNMATCHED_CONTACT: "Contact number not matched!",
  CLIENT_ID: "2",
  DIDNT_RECEIVE: "Didn’t Receive ? Resend in ",
  RESEND_OTP: "Resend OTP",
  PLEASE_WAIT: "Please wait...",
  ERROR: "Something went wrong!",
  SHOW_QR: "Show QR Code",
  SCAN_QR: "Scan QR Code",
  SELECT_LOCATION: "Select Location",
  OPEN_ISSUES: "Open Issues",
  RESOLVED_ISSUES: "Resolved Issues",
  ENTER_CUST_CODE_OR_NAME: "Enter Customer Code or Name",
  SELECT_BRANCH_LOCATION: "Select Branch Location",
  NO_RECORDS_FOUND: "No Records Found",
  ISSUE_TYPE: "Issue type : ",
  ISSUE_DESCRIPTION: "Issue description : \n",
  PENDING_WITH: "Pending With \n",
  RESOLVED_BY: "Resolved By \n",
  ISSUE_DATE: "Issue Date \n",
  CUSTOMER_VISIT: "Customer Visit",
  CUS_CODE: "Customer Code",
  REASON: "Reason of Visit",
  ONLY_REASON: "Reason",
  MEETING_MODE: "Mode of Contact",
  VISITING_EXE: "Visiting Executive",
  CUSTOMER_CONTACT: "Contact Number",
  PLANNED_BY: "Planned By",
  REQUIRED: "Required!",
  SEARCH_PLACEHOLDER_CV: "Enter text to search",
  VISITS_PLACEHOLDER: "Enter Customer Code or Name or Executive's Name",
  APPLY_FILTERS: "Apply Filters",
  ALREADY_REGISTERED: "Already registered user",
  PLANNEDTAB: "Plan",
  UPCOMINGTAB: "upcoming",
  EXECUTEDTAB: "executed",
  PLEASEENTER: "Please enter customer code or executive name",
  RESULTS: "Results",
  CLEAR: "Clear",
  NO_MATCHING_RECORD_FOUND: "No Matching Record Found.",
  CREATE_CUSTOMER_PROFILE: "Create Customer Profile",
  ENTER_CUSTOMER_DETAILS: "Enter Customer Details",
  ENTER_CUSTOMER: "Enter Customer Code *",
  ENTER_COMPANY_NAME: "Enter Company Name *",
  SELECT_CUSTOMER: "Select Customer",
  SEGMENT: "Segment *",
  SUB_SEGMENT: "Sub Segment *",
  TYPE: "Type *",
  SUB_TYPE: "Sub Type *",
  SELECT_STATUS_CUSTOMER: "Select Status of Customer *",
  BUTTON: "Button",
  ENTER_PAN_CARD: "Enter PAN CARD Number",
  ENTER_GST: "Enter GST Number",
  WEBSITE_LINK: "Website Link *",
  GST_NUMBER: "GST Number",
  PROCEED: "Proceed",
  TAG_LOCATION_NAME: "Tag Location Name",
  LOCATION_NAME: "Location Name",
  UPLOAD_VIDEO_IMAGE: "Upload Video/Image",
  UPLOAD_MEDIA: "Upload Media",
  INCLUDING_PNG: "(including png, jpeg, mp4, mov: max 25 mb)",
  SAVE_PROCEED: "Save & Proceed",
  NO_CUSTOMER_FOUND: "No Customer Found In 10 Km Distance",
  LOCATE_ME: "Locate Me",
  UPLOAD_VISITING_CARD: "Upload Visiting Card",
  SAIL_WEBSITE_LINK: "https://www.sail.co.in/en",
  UPDATE_DETAILS: "Update Details",
  MARKED_ESCALATION_AS_RESOLVED: "Marked Escalation as resolved",
  COMMENT_BY_ESCALATED_MAN: "Comment by Escalated Manager",
  COMMENT_BY_ESCALATED_MAN_COMES_HERE:
    "Comment by Escalated Manager comes here.",
  RESOLUTION_CMNT: "Resolution Comment",
  RESOLUTION_CMNT_HERE: "Resolution comment comes here ",
  ADD_CUSTOMER_REP: "Add Customer Representative",
  PLUS__CUSTOMER_REP: "+   Add Customer Representative",
  ADD_COMPETITOR_DETAILS: "Add Competitor Details",
  0: "0",
  3: "/03",
  ENTER_ADDRESS: "Enter Address *",
  ENTER_COMMENTS: "Enter Comments *",
  ERROR_MESSAGE:
    "Min 8 letters with atleast a symbol (@,!,&,#,%), uppercase, lowercase and a number",
  NOT_AVAILABLE: "Not Available",
  COMING_SOON: "Coming Soon",
  LOGIN_WITH_BIOMETRIC: "Login with Biometric",
  SELECT_CUST_REGION: "Select Customer Region *",
  MOBILE_NO_MISMATCH: "Mobile No. mismatch as per SAP",
  ENTER_DESIGNATION: "Enter Designation *",
  ENTER_DEPARTMENT: "Enter Department *",
  ENTER_EMAIL_ADDRESS: "Enter Email Address",
  ENETR_CONTACTNO: "Enter Contact Number",
  ENETR_WHATSAPP_NO: "Enter Whatsapp Number",
  INCLUDING_PNG_VISITING: "(including png, doc, pdf max 2mb)",
  LOCATION_CAPTURED: "Location Captured Successfully!",
  CANCELLED: "Cancelled",
  SELECT_CLUSTER: "Select Cluster *",
  DAY_WISE_STOCK: "Day Wise Stock *",
  PRICE_FEEDBACK_COMPETITOR: "Price Feedback of Competitor *",
  PROCURED_PRODUCTS: "Procured Products *",
  TENTATIVE_QUALITY_PROCURED: "Tentative Quality Procured *",
  SUPPLIER: "Supplier *",
  PROJECT_DETAILS: "Project Details *",
  INVALID: "Invalid",
  PAN: "PAN Card Number",
  GST: "GST Number",
  URL: "URL",
  WHATSAPPNO: "Whatsapp Number",
  CUST_PROFILE_SUCCESS: "Customer profile created successfully.",
  COMPANY_NAME: "Company Name",
  RE_UPLOAD: "Re-upload",
  ASTERISK: "*",
  IS_REMEMBER: "isRemember",
  NOTIFY_LENGTH: "notifyLength",
  CMNT: "Comments",
  ADD: "Address",
  COMP_NAME: "Company Name",
  CUSTOMER_ALREADY_EXISTS: "Customer profile already exists.",
  CREATE_MEETING_DETAILS: "Create Meeting Details",
  PLANNED_VISITS: "For Planned Visits",
  CUST_NAME: "Customer Name",
  VISIT_TIME: "Visit Time",
  OTHER_REASON: "Other Reason",
  SPEAK_POINTS: "Enter or Speak Discussion Points",
  CUST_REGION: "Customer Region",
  CUSTOMER_NAME: "Customer Name",
  DISCUSSION_POINTS: "Enter or Speak Discussion Points",
  ADD_ACCOMPANYING_EXECUTIVES: "Add Accompanying Executives",
  ADD_EXECUTIVE: "Add Executives",
  SELECT_ISSUE: "Select Issue",
  ESCALATED_TO: "Escalated to",
  ESCALATION_COMMENT: "Escalation Comment",
  UNPLANNED_VISIT: "Add Unplanned Visit",
  ADD_CCOMPANYING: "Add Accompanying Executive",
  UN: "Username",
  USER_UPN: "UPN",
  DONE: "Done",
  COMMENT: "Comment",
  ESCALATED_COMMENT: "Escalated Comment ",
  MARK_AS_RESOLVED: "Mark as Resolved",
  ADD_ANOTHER: "Add Another Issue +",
  SELECT_REPRE: "Select Representative",
  ADD_REPRE: "Add Representative",
  PLUS: "+",
  CREATE_VISIT_PLAN: "Create Visit Plan",
  MEETING_DETAILS_CREATED: "Meeting details created successfully.",
  ISSUE_CMNT: "Issue comment",
  FWD_BY: "Forward by",
  FWD_TO: "Forward To",
  ADD_CMNT: "Add Comments",
  ONLY_RESOLVED: "Resolved",
  ONLY_PENDING: "Pending",
  DOWNLOAD_PDF_REPORT: "Download PDF Report",
  CUST_REPRESENTATIVE: "Customer Representative",
  NO_DATA_FOUND: "No Data Found",
  MESSAGE_DETAILS: "Message Details",
  ACCOUNT_CR_SUCC: "Account created successfully.",
  VISIT_CREATE_SUCCESSFULLY: "Visit Created Successfully",
  DASHBOARD: "DASHBOARD",
  DOWNLOAD_FULL_PDF: "Download Full Report",
  MOU_BRANCH: " MoU Branch",
  MOU_QUANTITY: "MoU Quantity",
  TOTAL_QUANTITY: "Total Quantity",
  FULL_FILL: "Full Fill %",
  ESCA_BY: "Escalated By",
  CUS_PO: "Customer PO",
  PO_DATE: "PO Date",
  TOTAL_PO: "Total PO Quantity",
  PENDING_PO: "Pending PO Quantity",
  MP_Number: "Pending PO MP Number",
  Final_Quantity: "Pending PO Final Quantity",
  Dispatched_Quantity: "Pending PO Dispatched Quantity",
  Balance_Quantity: "Pending PO Balance Quantity",
  Customer: "Pending PO Customer",
  Branch: "Pending PO Branch",
  Total_Due: "Pending PO Total Due",
  Due_Type: "Pending PO Due Type",
  Total_Amount: "Pending PO Total Amount",
  Utilized: "Pending PO Utilized",
  Balance: "Pending PO Balance",
  From_Date: "Pending PO From Date",
  To_Date: "Pending PO To Date",
  Product: "Pending PO Product",
  Total_Offtake: "Pending PO Total Offtake",
  MANUFACTURING_PLANT: "Manufacturing Plant",
  FINAL_RETURN_QUANTITY: "Final Return Quantity",
  COMPLAIN_STATUS: "Complaint Status",
  DEFECT_TYPE: "Defect Type",
  ONLY_BRANCH: "Branch",
  ONLY_CUSTOMER: "Customer",
  ONLY_Total_Due: "Total Due",
  ONLY_Due_Type: "Due type",
  ONLY_From_Date: "From Date",
  ONLY_To_Date: "To Date",
  ONLY_PRODUCT: "Product",
  TOTAL_OFFTAKE: "Total Offtake",
  ONLY_MP: "MP Number",
  ONLY_FINAL_QUANTITY: "Final Quantity",
  ONLY_DISPATCH_QUANTITY: "Dispatched Quantity",
  ONLY_BALANCE_QUANTITY: "Balance Quantity",
  BRANCH_DESC: "Branch Description",
  MOU_BRANCH_DESC: "MoU Branch Description",
  ONLY_Total_Amount: "Total Amount",
  ONLY_Utilized: "Utilized",
  ONLY_Amount: "Amount",
  NO_DATA_FETCHED: "No Data Fetched",
  NO_CUS_NAME_EXISTS: "No customer with this name exists",
  PLEASE_CONNECT_VPN: "Please connect with VPN!",
  DOWNLOAD: "Downloaded",
  PLEASE_CHECK: "Please check your connection!",
  CANCEL_VISIT_SUCCESS: "Cancel Visit Successfully",
  EDIT_VISIT_SUCCESS: "Edit Visit Successfully",
  PLEASE_MARK_THE_ISSUE: "Please mark the issue as resolve",
  UPDATE_LOGOUT: "Your details has been updated, Please login again",
  SAP_CODE_UPDATE_MSG: "The customer code must be 10 digits.",
  ENTER_PAN_GST: "Please enter PAN and GST number",
  BACK_TO_HOME:"Back to Home",
  UPCOMING_VISIT:"Upcoming Visits",
  SARANSH:"SARANSH VERMA",
  PLANNED_VISIT:"Planned Visits",
  EXECUTED_VISIT:"Executed Visits",
  STAINLESS:"Stainless Steel Products",
  COLD_ROLLED:"Cold Rolled Products",
  EMPTY:"",
  SALES_ORDER:"Sales Order Status",
  MOU_STATUS:"MOU Status",
  CATEGORY:"Category",
  USER_ENQUIRY:"User Enquiry",
  ISSUE_ENQUIRY:"Issue Enquiry",
  NUMBER:"1234567",
  CUSTOMER_TYPE_TITLE:'Customer Type Title',
  TITLE:'Title',
  KIARA_SHARMA:"Kiara Sharma",
  LOREM_TEXT:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  TODAY:"Today",
  YESTERDAY:"Yesterday",
  VISIT_PLAN_WITH:"Visit Planned with Sahil Sharma",
  MODE_OF_CONDUCT:"Mode of Conduct",
  ONLINE:'Online',
  MEETING_SUCCESS:"Meeting Successful",
  VISIT_FOR_FINAL_AGGRE:"Visit for Final Agreement",
  SV:'SV',
  BRANCH_MANAGER:"Branch Mananger",
  CMS:"CMS",
  LOREM_LARGE:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta minus deleniti non voluptate vitae a, vero officiis, ab quos tempora expedita itaque velit neque dolor veniam et, repudiandae quam suscipit",
  OPERATIONS:'Operations',
  PRODUCT_MIX_MARKETING:"Product Mix and Marketing",
  MANAGEMENT_TEAM:"Management Team",
  CONTACT:'Contact',
  WEBSITE:'Website',
  NEARBY_CUSTOMERS:'Nearby Customer',
  ENTER_TEXT_TO_SEARCH:'Enter Text To Search',
  UPCOMING:'Upcoming',
  PLANNED:'Planned',
  EXECUTED:'Executed',
  XYZ_STEELWORKS:'XYZ Steelworks Private Limited',
  CUSTOMER_VISIT_1:'Customer Visit 1',
  ADD_UNPLANNED:'Add Unplanned Visit',
  FOR_PLANNED:'For Planned Visit',
  ENTER_PERSONAL_NAME:'Enter Personal Name',
  SELECT_DEP:'Select Departement',
  ENTER_NAME_NUMBER:'Enter Name Followed by 10 digits number',
  SELECT_CUSTOMER_CONTACT_DETAILS:'Select Customer Contact Details',
  CUSTOMER_NUMBERIC_CODE:"Customer Code: 123678",
  CUSTOMER_PROFILE_UPDATED_SUCCESSFULLY:'Customer Profile Successfully Updated',
  CUSTOMER_SEG:'Customer Segment',
  CUSTOMER_SUB_SEG:'Customer Sub Segment',
  CUSTOMER_SUB_TYPE:'Customer Sub Type',
  VIEW_CUSTOMER_PROFILE:'View Customer Profile',
  PLS_ENTER_GST_PAN:'Please enter GST and PAN number',
  ONE:'1',
  TWO:'2',
  THREE:'3',
  CUSTOMER_REPRESENTATIVE:'Customer Representative',
  COMPETITOR_1:'Competitor 1',
  ADD_TAG_LOCATION:"Add Tag Name to Selected Location",
  PNG_MP4 :'(including png, mp4, mov max 2 mb)',
  SOMETHING_WRONG:'Something went wrong',
  WE_ENCOUNTER:`We encountered an error while trying to connect with our server.\n Please try again after sometime.`,
  RELOAD:'Reload',
  OOPS:'Ooops!',
  NO_INTERNET_MSG:'No Internet Connection found \n Check your connection',
  PLUS_COMPETITOR:'+   Add Competitor',
  FOR_PLANNED_VISIT:'For Planned Visit',
  FOR_UNPLANNED_VISIT:'For Unplanned Visit',
  EXISTING_CUSTOMER:'Existing \n Customer',
  NEW_CUSTOMER:'New \n Customer',
  HOW_I_GET_ENLISTED:"How do i get Enlisted" ,
  THIRD_PARTIES:"What are 'Third Parties'?",
  INFORMATION_MEANS:"What does information mean?" ,
  NOT_DISCOSURE:"What is not open to disclosure?",
  CUSTOMER_PROFILE_CREATED_SUCCESSFULLY:'Customer Profile Created Successfully',
  CUSTOMER_CODE_NUMBER:'Customer Code-4773787',
  PLEASE_ENTER_INFORMATION:'Please enter details to sign in',
  FORWARD:'Forward',
  BACKWARD:'Backward',
  APR_24:'24 Apr',
  YOUR_EMAIL_ID:'Your Email Id',
  ENTER_YOUR_PERSONAL_INFO:'Enter Your Personal Information',
  UPN_ERROR_MSG:'Enter Valid UPN Number',
  CONTACT_ERROR_MSG:'Enter Valid Contact Number',
  NAME_ERROR_MSG:'Enter a Valid Name',
  EMAIL_ERROR_MSG:'Enter a Valid Email Address',
  LOCATION_ERROR_MSG:'Select a Valid Location',
  ROLE_ERROR_MSG:'Select a Valid Role',
  NOT_AVL:'N/A',
  SALES_ORDER_STATUS:'Sales Order Sttaus',
  DIRECT_DISPATCH:'Direct Dispatch Order Status',
  DUE_AND_OVERDUE:'Due and Overdue position (Outstanding summary)',
  LAST_VISIT_DETAIL:'Last Visit Details of the Customer',
  OFF_TAKE_REPORT:'Off take report',
  LC_BG:'LC/BG utilization report',
  QUALITY_COMPLAIN:'Quality Complain Status',
  ESCALATED_BY:'Escalated by',
  CUSTOMER:'Customer :',
  RIGHT:'Right',
  LEFT:'Left',
  INVALID_CUST_CODE:'InvalidCustomerCode',
  INVALID_GST:'Invalid GST Number',
  INVALID_PAN:'Invalid PAN Number',
  CUSTOMER_TYPE_PROJECT:"Type Project",
  CUSTOMER_TYPE_TRADER_DEFENCE:"Type Dealer Trader",
  INVALID_DESIGNATION:"Invalid Designation",
  INVALID_DEPARTEMENT:"Invalid Departement",
  INVALID_ADDRESS:"Invalid Address",
  PLEASE_ADD_COMMENT:'Please Add Cmment',
  SEARCH_BY:'Search by',
  DURATION:'Duration',
  DATA_RANGE:'Data Range',
  SEVEN_DAYS:'7 Days',
  FIFTEEN_DAYS:'15 Days',
  THIRTY_DAYS:'30 Days',
  ENTER_10_DIGIT_CUST_CODE:'Enter 10 digits customer code',
  PLEASE_SELECT_CUSTOMER_REGION:'Please Select Customer Region',
  PLEASE_SELECT_VISITING_EXECUTIVE:"Please Select Visiting Executive",
  PLEASE_SELECT_VISIT_DATE:'Please Select Visit date',
  PLS_REASON:'Please Select Visit Reason',
  PLS_MOC:'Please Select Mode of Contact',
  PLS_REMARKS:'Please Enter Remarks',
  FINGER_PRINT_KEY:'Finger Print Key',
  INVALID_WEBSITE:'Invalid Website',
 



  
  

};

export default StringConstants;
