import Glyphs from "assets/Glyphs";

const Data = [
  { key:1,
    uppertext: "Customer Code",
    lowertext: "987654321",
    imagepath: Glyphs.Code,
  },
  { key:2,
    uppertext: "Visit Date",
    lowertext: "03/03/2023",
    imagepath: Glyphs.VisitDate,
  },
  { key:3,
    uppertext: "Contact Number",
    lowertext: "+91-9999-123-456",
    imagepath: Glyphs.BluePhone,
  },
  { key:4,
    uppertext: "Reason of Visit",
    lowertext: "General Inquiry",
    imagepath: Glyphs.VisitDateIcon,
  },
  { key:5,
    uppertext: "Mode of Meeting",
    lowertext: "In-person",
    imagepath: Glyphs.Note,
  },
  { key:6,
    uppertext: "Visiting Executive",
    lowertext: "John Doe",
    imagepath: Glyphs.SignleUser,
  },
  { key:7,
    uppertext: "Location",
    lowertext: "Sector 11, Noida",
    imagepath: Glyphs.blueLocation,
  },
  { key:8,
    uppertext: "Email ID",
    lowertext: "john.doe@sail.in",
    imagepath: Glyphs.BlueEmail,
  },
  { key:9,
    uppertext: "Planned by",
    lowertext: "John6Doe",
    imagepath: Glyphs.SignleUser,
  },
]
export default Data;